# NumPy Practice

This notebook offers a set of exercises for different tasks with NumPy.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [NumPy documentation](https://numpy.org/devdocs/user/index.html).

And if you get stuck, try searching for a question in the following format: "how to do XYZ with numpy", where XYZ is the function you want to leverage from NumPy.

In [2]:
# Import NumPy as its abbreviation 'np'
import numpy as np 

In [3]:
# Create a 1-dimensional NumPy array
array_1d = np.array([1, 2, 3, 4, 5])

# Create a 2-dimensional NumPy array
array_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Create a 3-dimensional Numpy array
array_3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])


In [4]:
# Attributes of 1-dimensional array (shape, 
# number of dimensions, data type, size and type)
print("Shape:", array_1d.shape)
print("Number of Dimensions:", array_1d.ndim)
print("Data Type:", array_1d.dtype)
print("Size:", array_1d.size)
print("Type:", type(array_1d))


Shape: (5,)
Number of Dimensions: 1
Data Type: int64
Size: 5
Type: <class 'numpy.ndarray'>


In [5]:
# Attributes of 2-dimensional array
print("Shape:", array_2d.shape)
print("Number of Dimensions:", array_2d.ndim)
print("Data Type:", array_2d.dtype)
print("Size:", array_2d.size)
print("Type:", type(array_2d))

Shape: (3, 3)
Number of Dimensions: 2
Data Type: int64
Size: 9
Type: <class 'numpy.ndarray'>


In [6]:
# Attributes of 3-dimensional array
print("Shape:", array_3d.shape)
print("Number of Dimensions:", array_3d.ndim)
print("Data Type:", array_3d.dtype)
print("Size:", array_3d.size)
print("Type:", type(array_3d))

Shape: (2, 2, 3)
Number of Dimensions: 3
Data Type: int64
Size: 12
Type: <class 'numpy.ndarray'>


In [7]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
import pandas as pd
df = pd.DataFrame(array_2d)


In [8]:
# Create an array of shape (10, 2) with only ones
ones_array = np.ones((10,2))

In [9]:
# Create an array of shape (7, 2, 3) of only zeros
zeroes_array = np.zeros((7,2,3))

In [10]:
# Create an array within a range of 0 and 100 with step 3
range_array = np.arange(0,100,3)

In [11]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
random_array = np.random.randint(0,11,size=(7,2))

In [13]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
random_float_array = np.random.rand(3,5)


[[0.28284505 0.72287143 0.21515361 0.89206238 0.10256053]
 [0.6852887  0.41586663 0.06344843 0.54812337 0.99099256]
 [0.58295811 0.2876163  0.34696816 0.89978489 0.07015575]]


In [14]:
# Set the random seed to 42
np.random.seed(42)

# Create a random array of numbers between 0 & 10 of size (4, 6)
random_array_with_seed = np.random.randint(0, 11, size=(4, 6))


Run the cell above again, what happens?

Are the numbers in the array different or the same? Why do think this is?

In [15]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable
random_numbers_array = np.random.randint(1, 11, size=(3, 7))

# Find the unique numbers in the array you just created
unique_numbers = np.unique(random_numbers_array)

In [16]:
# Find the 0'th index of the latest array you created
element_at_zero_index = random_numbers_array[0, 0]

In [17]:
# Get the first 2 rows of latest array you created
first_two_rows = random_numbers_array[:2, :]

In [18]:
# Get the first 2 values of the first 2 rows of the latest array
first_two_values = random_numbers_array[:2, :2]


In [19]:
# Create a random array of numbers between 0 and 10 of size (3, 5)
random_array = np.random.randint(0, 11, size=(3, 5))

# Create an array of ones of size (3, 5)
ones_array = np.ones((3, 5))

In [20]:
# Add the two arrays together
result_array = random_array + ones_array


In [27]:
# Create another array of ones of shape (5, 3)
onother_ones_array = np.ones((5, 3))


In [29]:
# Try add the array of ones and the other most recent array together
ones_array_5x3_transposed = onother_ones_array.T

sum_array = ones_array_5x3_transposed + ones_array

When you try the last cell, it produces an error. Why do think this is?

How would you fix it?

In [33]:
# Create another array of ones of shape (3, 5)
new_array_3_5 = np.ones((3,5))

In [34]:
# Subtract the new array of ones from the other most recent array
result = new_array_3_5 - ones_array

In [35]:
# Multiply the ones array with the latest array
result = result * ones_array

In [36]:
# Take the latest array to the power of 2 using '**'
result = result**2

In [38]:
# Do the same thing with np.square()
result = np.square(result)

In [39]:
# Find the mean of the latest array using np.mean()
mean = np.mean(result)

In [40]:
# Find the maximum of the latest array using np.max()
max = np.max(result)

In [41]:
# Find the minimum of the latest array using np.min()
min = np.min(result)

In [42]:
# Find the standard deviation of the latest array
std = np.std(result)

In [43]:
# Find the variance of the latest array
var = np.var(result)

In [44]:
# Reshape the latest array to (3, 5, 1)
reshaped_array = np.reshape(result,(3,5,1))

In [46]:
# Transpose the latest array
transposed = np.transpose(result)

What does the transpose do?

In [48]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)
array_3x3 = np.random.randint(0, 11, size=(3, 3))
array_3x2 = np.random.randint(0, 11, size=(3, 2))

In [53]:
# Perform a dot product on the two newest arrays you created
dot_product_result = np.dot(array_3x3, array_3x2)


In [55]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)
array1 = np.random.randint(0, 11, size=(4, 3))

array2 = np.random.randint(0, 11, size=(4, 3))

In [56]:
# Perform a dot product on the two newest arrays you created
res = np.dot(array1,array2)

ValueError: shapes (4,3) and (4,3) not aligned: 3 (dim 1) != 4 (dim 0)

It doesn't work. How would you fix it?

In [57]:
# Take the latest two arrays, perform a transpose on one of them and then perform 
# a dot product on them both
arr1_transposed = np.transpose(array1)
res = np.dot(arr1_transposed,array2)

Notice how performing a transpose allows the dot product to happen.

Why is this?

Checking out the documentation on [`np.dot()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) may help, as well as reading [Math is Fun's guide on the dot product](https://www.mathsisfun.com/algebra/vectors-dot-product.html).

Let's now compare arrays.

In [38]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables
array1 = np.random.randint(0, 11, size=(4, 3))

array2 = np.random.randint(0, 11, size=(4, 3))

In [58]:
# Compare the two arrays with '>'
comparison_result = array1 > array2

What happens when you compare the arrays with `>`?

In [59]:
# Compare the two arrays with '>='
comparison_result = array1 >= array2

In [60]:
# Find which elements of the first array are greater than 7
greater_than_7 = array1 > 7


In [61]:
# Which parts of each array are equal? (try using '==')
equality_result = array1 == array2


In [43]:
# Sort one of the arrays you just created in ascending order
sorted_array = np.sort(array1)


In [62]:
# Sort the indexes of one of the arrays you just created
sorted_indices = np.argsort(array1, axis=None)


In [63]:
# Find the index with the maximum value in one of the arrays you've created
max_index = np.argmax(array1)


In [64]:
# Find the index with the minimum value in one of the arrays you've created
max_index = np.argmin(array1)


In [65]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created
max_indices_axis1 = np.argmax(array1, axis=1)


In [66]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created
min_indices_axis0 = np.argmin(array1, axis=0)


In [68]:
# Create an array of normally distributed random numbers
mean = 0 
std_dev = 1  
size = (3, 4) 

normal_array = np.random.normal(mean, std_dev, size)

In [69]:
# Create an array with 10 evenly spaced numbers between 1 and 100
evenly_spaced_array = np.linspace(1, 100, 10)


## Extensions

For more exercises, check out the [NumPy quickstart tutorial](https://numpy.org/doc/stable/user/quickstart.html). A good practice would be to read through it and for the parts you find interesting, add them into the end of this notebook.

Pay particular attention to the section on broadcasting. And most importantly, get hands-on with the code as much as possible. If in dobut, run the code, see what it does.

The next place you could go is the [Stack Overflow page for the top questions and answers for NumPy](https://stackoverflow.com/questions/tagged/numpy?sort=MostVotes&edited=true). Often, you'll find some of the most common and useful NumPy functions here. Don't forget to play around with the filters! You'll likely find something helpful here.

Finally, as always, remember, the best way to learn something new is to try it. And try it relentlessly. If you get interested in some kind of NumPy function, asking yourself, "I wonder if NumPy could do that?", go and find out.